using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using PassbookManagement.Framework;

/* This is the data transfer object for Login Account.
 */

namespace PassbookManagement.Models
{
    public class LoginAccount
    {
        //username is auto generated by code
        [Key]
        public string Username { get; set; }

        [StringLength(10)]
        public string Decent { get; set; }

        [Required]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$")]
        public string Password { get; set; }

        //foreign key
        [ForeignKey("Customer")]
        public string UserRefId { get; set; }
        public Customer Customer { get; set; }

    }
}
